"""Small semantic palette for KAgent's live Textual UI."""

PRIMARY = "#D6DEE8"
MUTED = "#7E8A9A"
ACCENT = "#38BDF8"
SUCCESS = "#3FB950"
WARNING = "#F59E0B"
ERROR = "#EF4444"
DANGER = "#F43F5E"
LINK = "#60A5FA"

BOLD_ACCENT = f"bold {ACCENT}"
BOLD_SUCCESS = f"bold {SUCCESS}"
BOLD_ERROR = f"bold {ERROR}"
BOLD_DANGER = f"bold {DANGER}"
